version: '3.8'

services:

  web:
    container_name: web
    build:
      context: src
      dockerfile: Dockerfile
    command: python manage.py runserver  0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app/
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}